### ISSUE TITLE
Resources$NotFoundException after WearManager.initialize(this)

### ISSUE THREAD

**Issue by iglaweb** [googlesamples/android-WearCompanionLibrary#7]
I've found such issue in Developer Console. It's not a massive problem, but better to fix it. I look through the source code, it seems to be ok. How do you think?

This error is thrown after WearManager.initialize(this) in Application class.

```
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f0b0188
	at android.content.res.Resources.getText(Resources.java:306)
	at android.content.res.Resources.getString(Resources.java:392)
	at android.content.Context.getString(Context.java:377)
	at com.google.devrel.wcl.n.<init>(SourceFile:121)
	at com.google.devrel.wcl.n.a(SourceFile:168)
```

Problem devices: Xperia M2 (D2303) Android 5.1, Galaxy Ace3, Xperia™ M4 Aqua Dual (E2333) 

WCL version: 1.1

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
